sonar.projectKey=Meghana-Kalwal_DVWA
sonar.organization=meghana-kalwal
sonar.projectName=DVWA - Damn Vulnerable Web Application

sonar.sources=.
sonar.exclusions=vendor/**,docs/**,external/**,**/*.md,**/*.txt,**/*.pdf,*.ico,**/*.png,**/*.jpg,**/*.gif,**/*.css

sonar.php.version=8

sonar.sourceEncoding=UTF-8
sonar.scm.provider=git

sonar.php.file.suffixes=.php
