name: SAST + SARIF Upload

on:
  push:
    branches: ["main"]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Scan (Generate SARIF)
        run: |
          semgrep scan --config=auto --sarif --output=results.sarif

      - name: Check file exists (DEBUG)
        run: ls -l

      - name: Upload SARIF File
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif




